[package]
name = "qwerk"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5.9"
crossbeam-queue = "0.3.9"
crossbeam-utils = "0.8.17"
parking_lot = "0.12.1"
scc = "2.0.6"
static_assertions = "1.1.0"
thiserror = "1.0.51"

[dev-dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
